name: Build from Trunk

on:
  push:
    branches: [ "trunk" ]

permissions:
  contents: write
  packages: write

env:
  GPR_PUBLISH: true
  GLASS_MAVEN_PUBLISH: true
  MODRINTH_PUBLISH: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew build

      - name: Deploy release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Current Trunk Snapshot"
          files: |
            build/libs/*.jar

      - name: Publish maven package
        run: ./gradlew upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GLASS_MAVEN_USERNAME: ${{ secrets.GLASS_MAVEN_USERNAME }}
          GLASS_MAVEN_PASSWORD: ${{ secrets.GLASS_MAVEN_PASSWORD }}